# Generated by Django 3.1.3 on 2021-04-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('ci_idcita', models.AutoField(primary_key=True, serialize=False)),
                ('ci_cuenta', models.CharField(max_length=10)),
                ('ci_fechacita', models.DateTimeField(blank=True, null=True)),
                ('ci_orden', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('ci_horatencion', models.CharField(blank=True, max_length=5, null=True)),
                ('ci_observaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('ci_indicatencion', models.CharField(blank=True, max_length=5, null=True)),
                ('ci_edad', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('ci_tipopac', models.CharField(blank=True, max_length=5, null=True)),
                ('ci_tipomov', models.CharField(blank=True, max_length=3, null=True)),
                ('ci_actividad', models.CharField(blank=True, max_length=3, null=True)),
                ('ci_estado', models.CharField(blank=True, max_length=1, null=True)),
                ('ci_facturada', models.IntegerField(blank=True, null=True)),
                ('ci_pagada', models.IntegerField(blank=True, null=True)),
                ('ci_atend', models.TextField(blank=True, null=True)),
                ('ci_terminal', models.CharField(blank=True, max_length=15, null=True)),
                ('ci_userterm', models.CharField(blank=True, max_length=15, null=True)),
                ('ci_usersisa', models.CharField(blank=True, max_length=15, null=True)),
                ('ci_fecpro', models.DateTimeField(blank=True, null=True)),
                ('ci_indatos', models.IntegerField(blank=True, null=True)),
                ('ci_dxcie', models.CharField(blank=True, max_length=6, null=True)),
                ('ci_dxcie2', models.CharField(blank=True, max_length=6, null=True)),
                ('ci_tarifaexamen', models.CharField(blank=True, max_length=2, null=True)),
                ('ci_tarifa', models.CharField(blank=True, max_length=3, null=True)),
                ('ci_contratante', models.CharField(blank=True, max_length=6, null=True)),
                ('ci_numfac', models.CharField(blank=True, max_length=12, null=True)),
                ('ci_coaseg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ci_cofarm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ci_coserv', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ci_nroid', models.CharField(blank=True, max_length=12, null=True)),
                ('ci_paciente', models.CharField(blank=True, max_length=98, null=True)),
                ('ci_codsx', models.CharField(blank=True, max_length=1, null=True)),
                ('ci_coded', models.IntegerField(blank=True, null=True)),
                ('ci_tel1', models.CharField(blank=True, max_length=15, null=True)),
                ('ci_tel2', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('pr_numero', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('pr_fecha', models.CharField(blank=True, max_length=10, null=True)),
                ('pr_estado', models.CharField(blank=True, max_length=1, null=True)),
                ('pr_cupos', models.IntegerField(blank=True, null=True)),
                ('pr_minutos', models.IntegerField(blank=True, null=True)),
                ('pr_tipo', models.CharField(blank=True, max_length=1, null=True)),
                ('pr_fechareg', models.DateTimeField(auto_now_add=True, null=True)),
                ('pr_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('pr_observ', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'programacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'citas_reporter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActoMedico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idcita', models.IntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('problema', models.TextField(blank=True, null=True)),
                ('parterial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fcardiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frespiratoria', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tbucal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxiliar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('icorporal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pcefalico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('examen', models.TextField(blank=True, null=True)),
                ('planes', models.TextField(blank=True, null=True)),
                ('destino', models.IntegerField(blank=True, null=True)),
                ('cod_final', models.CharField(blank=True, max_length=6, null=True)),
                ('des_fina', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'acto_medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AntecedentesActoMedico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idcita', models.IntegerField()),
                ('an_id', models.IntegerField()),
                ('an_valor', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'antecedentes_acto_medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoActoMedico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idcita', models.IntegerField()),
                ('idcie', models.IntegerField()),
                ('tdx', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnostico_acto_medico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantillaAgenda',
            fields=[
                ('orden', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora', models.CharField(blank=True, max_length=5, null=True)),
                ('horalleg', models.CharField(blank=True, max_length=15, null=True)),
                ('historia', models.CharField(blank=True, max_length=10, null=True)),
                ('paciente', models.CharField(blank=True, max_length=75, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('controla', models.CharField(blank=True, max_length=3, null=True)),
                ('fecha', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=50, null=True)),
                ('titular', models.CharField(blank=True, max_length=50, null=True)),
                ('idcita', models.IntegerField(null=True)),
                ('atend', models.CharField(blank=True, max_length=1, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=25, null=True)),
                ('cond_serv', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'plantilla_agenda',
                'managed': True,
            },
        ),
    ]
