# Generated by Django 3.1.3 on 2022-02-28 17:36

import Apps.Reclamos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ficheros', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('cr_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('cr_def_corta', models.CharField(blank=True, max_length=150, null=True)),
                ('cr_causa_espec', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('ds_cod', models.AutoField(primary_key=True, serialize=False)),
                ('ds_desc', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('er_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('er_desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('etr_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('etr_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedioRecepcion',
            fields=[
                ('mr_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('mr_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MotConcAnt',
            fields=[
                ('mc_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('mc_desc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NaturalezaMedida',
            fields=[
                ('nm_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('nm_desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcesoMedida',
            fields=[
                ('pm_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('pm_desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('rr_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('rr_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('sr_cod', models.AutoField(primary_key=True, serialize=False)),
                ('sr_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('sr_codsusalud', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_documento',
            fields=[
                ('td_cod', models.IntegerField(primary_key=True, serialize=False)),
                ('td_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tramas',
            fields=[
                ('tr_cod', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(blank=True, max_length=6, null=True)),
                ('trama', models.TextField(blank=True, null=True)),
                ('creador', models.CharField(blank=True, max_length=20, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificador', models.CharField(blank=True, max_length=20, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('re_cod', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=6, null=True)),
                ('cod_fisico', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=15, null=True)),
                ('medio', models.IntegerField(blank=True, null=True)),
                ('nro_documento', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=15, null=True)),
                ('nombres', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=150, null=True)),
                ('paterno', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=150, null=True)),
                ('materno', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=150, null=True)),
                ('nro_documento_p', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=15, null=True)),
                ('nombres_p', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=150, null=True)),
                ('paterno_p', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=150, null=True)),
                ('materno_p', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=150, null=True)),
                ('result_email', models.IntegerField(blank=True, null=True)),
                ('email', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=50, null=True)),
                ('domicilio', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=100, null=True)),
                ('telefono', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('detalle', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=1500, null=True)),
                ('compete', models.IntegerField(blank=True, null=True)),
                ('codigo_original', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=15, null=True)),
                ('derivado_tipo', models.IntegerField(blank=True, null=True)),
                ('derivado_codigo', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=8, null=True)),
                ('fecha_result', models.DateField(blank=True, null=True)),
                ('comunic_result', models.IntegerField(blank=True, null=True)),
                ('fecha_notif_result', models.DateField(blank=True, null=True)),
                ('creador', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=20, null=True)),
                ('creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('modificador', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=20, null=True)),
                ('modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('clasificacion1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clasificacion1', to='Reclamos.clasificacion')),
                ('clasificacion2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clasificacion2', to='Reclamos.clasificacion')),
                ('clasificacion3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clasificacion3', to='Reclamos.clasificacion')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ficheros.especialidades')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.estado')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.etapa')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ficheros.medicos')),
                ('medio_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.mediorecepcion')),
                ('mot_concl_antic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.motconcant')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.resultado')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.servicio')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_documento', to='Reclamos.tipo_documento')),
                ('tipo_documento_p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_documento_p', to='Reclamos.tipo_documento')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descripcion', Apps.Reclamos.models.EmptyToNone(blank=True, max_length=500, null=True)),
                ('fecha_implem', models.DateField(blank=True, null=True)),
                ('fecha_culm', models.DateField(blank=True, null=True)),
                ('naturaleza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reclamos.naturalezamedida')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reclamos.procesomedida')),
                ('re_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamo_id', to='Reclamos.reclamos')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='cr_derecho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Reclamos.derecho'),
        ),
    ]
