# Generated by Django 3.1.3 on 2021-01-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('padre', models.IntegerField()),
                ('accion', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('iduser', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('superadmin', models.BooleanField()),
                ('estado', models.BooleanField()),
                ('iduser', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rols',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenusRols',
            fields=[
                ('id_rol', models.OneToOneField(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='seguridad.rols')),
                ('iduser', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menus_rols',
                'managed': False,
            },
        ),
    ]
