# Generated by Django 3.1.3 on 2022-06-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FicherosGenerales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('mediodepagoid', models.AutoField(primary_key=True, serialize=False)),
                ('mediodepagocodigo', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('mediodepagonombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'mediodepago',
                'managed': False,
            },
        ),
    ]
