# Generated by Django 3.1.3 on 2021-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficheros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
