# Generated by Django 3.1.3 on 2021-03-15 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('iduser', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_formularioc', models.ForeignKey(db_column='id_formularioc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_formularioc', to='formulario.formularioc')),
                ('padre', models.ForeignKey(blank=True, db_column='padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_padre', to='menus.menu')),
            ],
            options={
                'db_table': 'menu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('iduser', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('menus', models.ManyToManyField(blank=True, related_name='rols', to='menus.Menu')),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
    ]
