# Generated by Django 3.1.3 on 2021-01-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formularioc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('fecharegistro', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='formulariod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=80)),
                ('controltype', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('order', models.IntegerField(null=True)),
                ('formularioc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularioc_id', to='formulario.formularioc')),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=5, null=True)),
                ('value', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('formulariod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulariod_id', to='formulario.formulariod')),
            ],
        ),
    ]
